"""Acceptance tests for MICRO-1.4. DO NOT EDIT THIS FILE.

Run: pytest tests/test_session.py -v
Needs: reachable Postgres via DATABASE_URL (async), migration applied.
"""

import inspect
import os

import pytest
from httpx import ASGITransport, AsyncClient
from sqlalchemy import text
from sqlalchemy.ext.asyncio import AsyncEngine, AsyncSession
import sys
from pathlib import Path

from src.models.session import AsyncSessionLocal, engine, get_db

pytestmark = pytest.mark.asyncio
PROJECT_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(PROJECT_ROOT))

HAS_DB = os.environ.get("DATABASE_URL") is not None


# ---------- engine + factory config (no live DB needed) ----------
@pytest.mark.asyncio
def test_engine_is_async():
    assert isinstance(engine, AsyncEngine)


def test_engine_uses_asyncpg():
    assert "asyncpg" in str(engine.url), "engine must use the asyncpg driver"


def test_pool_pre_ping_enabled():
    # pre_ping guards against dead connections after a DB restart
    assert engine.pool._pre_ping is True, "set pool_pre_ping=True"


def test_sessionmaker_expire_on_commit_false():
    assert (
        AsyncSessionLocal.kw.get("expire_on_commit") is False
    ), "expire_on_commit must be False for async — see the ticket"


def test_get_db_is_async_generator():
    assert inspect.isasyncgenfunction(get_db), "get_db must be an async generator"


# ---------- live session lifecycle ----------


async def test_get_db_yields_usable_session():
    agen = get_db()
    session = await agen.__anext__()
    try:
        assert isinstance(session, AsyncSession)
        result = await session.execute(text("SELECT 1"))
        assert result.scalar() == 1
    finally:
        await agen.aclose()


async def test_get_db_rolls_back_on_exception():
    """If the caller raises, the session must not commit a half-written unit."""
    agen = get_db()
    # simulate an error during the request by throwing into the generator
    with pytest.raises(ValueError):
        await agen.athrow(ValueError("boom"))
    # after rollback the session should be usable/closed, not stuck in a
    # broken transaction — a fresh query on a new session must work
    async with AsyncSessionLocal() as s:
        assert (await s.execute(text("SELECT 1"))).scalar() == 1


# ---------- health endpoint ----------


async def test_health_db_endpoint_ok():
    from src.main import app

    transport = ASGITransport(app=app)
    async with AsyncClient(transport=transport, base_url="http://test") as client:
        resp = await client.get("/health/db")
    assert resp.status_code == 200
    assert resp.json() == {"database": "ok"}
