"""Acceptance tests for MICRO-1.3. DO NOT EDIT THIS FILE.

Run: pytest tests/test_schemas.py -v
No database required — these are pure validation tests.
"""

from datetime import datetime, timedelta, timezone
from decimal import Decimal

import pytest
from pydantic import ValidationError

from src.models.schemas import (
    AnomalyResponse,
    EventBulkCreate,
    EventCreate,
    EventResponse,
    ErrorResponse,
    BatchReceipt,
)


def valid_event(**overrides) -> dict:
    base = {
        "event_type": "purchase",
        "user_id": 42,
        "amount": "199.99",
        "payload": {"channel": "mobile"},
        "occurred_at": datetime.now(timezone.utc) - timedelta(minutes=1),
    }
    base.update(overrides)
    return base


# ---------- EventCreate: happy path ----------


def test_valid_event_is_accepted():
    ev = EventCreate(**valid_event())
    assert ev.event_type == "purchase"
    assert ev.user_id == 42


def test_amount_may_be_omitted():
    payload = valid_event()
    payload.pop("amount")
    ev = EventCreate(**payload)
    assert ev.amount is None


def test_payload_may_be_omitted():
    payload = valid_event()
    payload.pop("payload")
    EventCreate(**payload)


# ---------- EventCreate: rejections ----------


def test_negative_amount_rejected():
    with pytest.raises(ValidationError):
        EventCreate(**valid_event(amount="-1.00"))


def test_amount_with_three_decimals_rejected():
    with pytest.raises(ValidationError):
        EventCreate(**valid_event(amount="10.999"))


def test_amount_with_too_many_digits_rejected():
    with pytest.raises(ValidationError):
        EventCreate(**valid_event(amount="12345678901.00"))  # 13 digits


def test_zero_user_id_rejected():
    with pytest.raises(ValidationError):
        EventCreate(**valid_event(user_id=0))


def test_negative_user_id_rejected():
    with pytest.raises(ValidationError):
        EventCreate(**valid_event(user_id=-5))


def test_unknown_event_type_rejected():
    with pytest.raises(ValidationError):
        EventCreate(**valid_event(event_type="hacking"))


def test_naive_datetime_rejected():
    naive = datetime.now()  # no tzinfo
    with pytest.raises(ValidationError):
        EventCreate(**valid_event(occurred_at=naive))


def test_far_future_timestamp_rejected():
    future = datetime.now(timezone.utc) + timedelta(hours=2)
    with pytest.raises(ValidationError):
        EventCreate(**valid_event(occurred_at=future))


def test_small_clock_skew_accepted():
    slightly_ahead = datetime.now(timezone.utc) + timedelta(minutes=2)
    ev = EventCreate(**valid_event(occurred_at=slightly_ahead))
    assert ev.occurred_at == slightly_ahead


def test_extra_field_rejected():
    with pytest.raises(ValidationError):
        EventCreate(**valid_event(sneaky_field="nope"))


@pytest.mark.parametrize(
    "server_owned",
    ["id", "ingested_at", "anomaly_score", "is_anomaly", "model_version"],
)
def test_server_owned_fields_not_settable(server_owned):
    """A client must not be able to claim a row is not an anomaly, etc."""
    assert (
        server_owned not in EventCreate.model_fields
    ), f"{server_owned} is server-owned and must not appear on EventCreate"


# ---------- EventBulkCreate ----------


def test_bulk_accepts_one_event():
    EventBulkCreate(events=[valid_event()])


def test_bulk_rejects_empty_list():
    with pytest.raises(ValidationError):
        EventBulkCreate(events=[])


def test_bulk_accepts_exactly_1000():
    batch = EventBulkCreate(events=[valid_event() for _ in range(1000)])
    assert len(batch.events) == 1000


def test_bulk_rejects_1001():
    with pytest.raises(ValidationError):
        EventBulkCreate(events=[valid_event() for _ in range(1001)])


def test_bulk_rejects_one_bad_event_among_good_ones():
    events = [valid_event() for _ in range(5)]
    events[3]["amount"] = "-99.00"
    with pytest.raises(ValidationError):
        EventBulkCreate(events=events)


# ---------- Response models ----------


class FakeORMEvent:
    """Stands in for a SQLAlchemy row — no DB needed."""

    id = 1
    event_type = "trade"
    user_id = 7
    amount = Decimal("50.00")
    payload = {"channel": "api"}
    occurred_at = datetime(2026, 7, 1, 12, 0, tzinfo=timezone.utc)
    ingested_at = datetime(2026, 7, 1, 12, 0, 5, tzinfo=timezone.utc)
    anomaly_score = 0.91
    is_anomaly = True
    model_version = "v1.0.0"


def test_event_response_from_orm_object():
    resp = EventResponse.model_validate(FakeORMEvent())
    assert resp.id == 1
    assert resp.is_anomaly is True
    assert resp.model_version == "v1.0.0"


def test_anomaly_response_from_orm_object():
    resp = AnomalyResponse.model_validate(FakeORMEvent())
    assert resp.anomaly_score == 0.91


def test_anomaly_response_has_exact_field_set():
    assert set(AnomalyResponse.model_fields) == {
        "id",
        "user_id",
        "amount",
        "occurred_at",
        "anomaly_score",
        "model_version",
    }


# ---------- Error + receipt contracts ----------


def test_error_response_requires_core_fields():
    err = ErrorResponse(
        error_code="VALIDATION_ERROR",
        message="Request payload failed validation.",
        request_id="abc-123",
    )
    assert err.details is None


def test_error_response_missing_request_id_rejected():
    with pytest.raises(ValidationError):
        ErrorResponse(error_code="X", message="y")


def test_batch_receipt_contract():
    receipt = BatchReceipt(batch_id=10, request_id="abc-123", accepted=999, rejected=1)
    assert receipt.accepted == 999


def test_batch_receipt_rejects_negative_counts():
    with pytest.raises(ValidationError):
        BatchReceipt(batch_id=1, request_id="a", accepted=-1, rejected=0)
