"""Acceptance tests for MICRO-2.1. DO NOT EDIT THIS FILE.

Run: TESTING=1 pytest tests/test_ingestion.py -v
Needs: reachable Postgres (async), migration applied.
"""

from datetime import datetime, timedelta, timezone

import pytest
from httpx import ASGITransport, AsyncClient
from sqlalchemy import func, select
from src.models.session import AsyncSessionLocal
from src.models.database import Event, IngestionBatch

pytestmark = pytest.mark.asyncio


def valid_event(**overrides) -> dict:
    base = {
        "event_type": "purchase",
        "user_id": 42,
        "amount": "199.99",
        "payload": {"channel": "mobile"},
        "occurred_at": (datetime.now(timezone.utc) - timedelta(minutes=1)).isoformat(),
    }
    base.update(overrides)
    return base


async def _client():
    from src.main import app

    return AsyncClient(transport=ASGITransport(app=app), base_url="http://test")


async def _count(table) -> int:
    async with AsyncSessionLocal() as s:
        return (await s.execute(select(func.count()).select_from(table))).scalar()


# ---------- happy path ----------


async def test_single_event_returns_202():
    async with await _client() as c:
        resp = await c.post("/events", json={"events": [valid_event()]})
    assert resp.status_code == 202
    body = resp.json()
    assert body["accepted"] == 1
    assert body["rejected"] == 0
    assert "batch_id" in body and "request_id" in body


async def test_thousand_events_accepted():
    events = [valid_event() for _ in range(1000)]
    async with await _client() as c:
        resp = await c.post("/events", json={"events": events})
    assert resp.status_code == 202
    assert resp.json()["accepted"] == 1000


# ---------- validation boundary (pydantic, no DB) ----------


async def test_1001_events_rejected():
    events = [valid_event() for _ in range(1001)]
    async with await _client() as c:
        resp = await c.post("/events", json={"events": events})
    assert resp.status_code == 422


async def test_empty_list_rejected():
    async with await _client() as c:
        resp = await c.post("/events", json={"events": []})
    assert resp.status_code == 422


async def test_malformed_event_rejected_and_nothing_inserted():
    before = await _count(Event)
    bad = valid_event(amount="-5.00")
    async with await _client() as c:
        resp = await c.post("/events", json={"events": [valid_event(), bad]})
    assert resp.status_code == 422
    after = await _count(Event)
    assert after == before, "no rows should be inserted when validation fails"


# ---------- persistence + audit ----------


async def test_events_actually_persisted():
    before = await _count(Event)
    events = [valid_event() for _ in range(5)]
    async with await _client() as c:
        resp = await c.post("/events", json={"events": events})
    assert resp.status_code == 202
    after = await _count(Event)
    assert after == before + 5


async def test_batch_row_created_with_request_id():
    rid = "test-req-abc-124"
    async with await _client() as c:
        resp = await c.post(
            "/events",
            json={"events": [valid_event()]},
            headers={"X-Request-ID": rid},
        )
    assert resp.status_code == 202
    assert resp.json()["request_id"] == rid

    async with AsyncSessionLocal() as s:
        row = (
            await s.execute(
                select(IngestionBatch).where(IngestionBatch.request_id == rid)
            )
        ).scalar_one_or_none()
    assert row is not None, "an ingestion_batches row must be written"
    assert row.event_count == 1
    assert row.completed_at is not None, "batch must be closed (completed_at set)"


async def test_atomicity_batch_and_events_consistent():
    """After a successful ingest, the batch's event_count matches reality."""
    events = [valid_event() for _ in range(7)]
    rid = "test-req-atomic-8"
    async with await _client() as c:
        resp = await c.post(
            "/events", json={"events": events}, headers={"X-Request-ID": rid}
        )
    assert resp.status_code == 202
    async with AsyncSessionLocal() as s:
        batch = (
            await s.execute(
                select(IngestionBatch).where(IngestionBatch.request_id == rid)
            )
        ).scalar_one()
    assert batch.event_count == 7
    assert batch.failed_count == 0
