"""Acceptance tests for MICRO-2.2. DO NOT EDIT THIS FILE.

Run: TESTING=1 pytest tests/test_cache.py -v
Needs: postgres + redis up, seeded events (anomalies present).
"""

from unittest.mock import patch

import pytest
from httpx import ASGITransport, AsyncClient

from src.services.cache import cache_delete, cache_get, cache_set

pytestmark = pytest.mark.asyncio


async def _client():
    from src.main import app

    return AsyncClient(transport=ASGITransport(app=app), base_url="http://test")


# ---------- cache wrapper primitives ----------


async def test_set_then_get_roundtrip():
    await cache_set("test:roundtrip", {"a": 1}, ttl=30)
    assert await cache_get("test:roundtrip") == {"a": 1}
    await cache_delete("test:roundtrip")


async def test_get_missing_key_returns_none():
    await cache_delete("test:definitely-not-here")
    assert await cache_get("test:definitely-not-here") is None


async def test_delete_removes_key():
    await cache_set("test:to-delete", {"x": 1})
    await cache_delete("test:to-delete")
    assert await cache_get("test:to-delete") is None


async def test_cache_get_never_raises_when_redis_down():
    """THE point of the ticket: a Redis failure must degrade, not explode."""
    with patch("src.services.cache._client") as fake:
        fake.get.side_effect = ConnectionError("redis is down")
        assert await cache_get("test:anything") is None  # no exception


async def test_cache_set_never_raises_when_redis_down():
    with patch("src.services.cache._client") as fake:
        fake.set.side_effect = ConnectionError("redis is down")
        assert await cache_set("test:anything", {"a": 1}) is False


# ---------- endpoint behaviour ----------


async def test_anomalies_endpoint_returns_list():
    async with await _client() as c:
        resp = await c.get("/anomalies?limit=5")
    assert resp.status_code == 200
    body = resp.json()
    assert isinstance(body, list)
    if body:
        assert {"id", "user_id", "occurred_at"} <= set(body[0])


async def test_second_call_is_served_from_cache():
    await cache_delete("anomalies:limit=7")
    async with await _client() as c:
        first = await c.get("/anomalies?limit=7")
        second = await c.get("/anomalies?limit=7")
    assert first.status_code == second.status_code == 200
    assert first.json() == second.json()
    # the key must now exist — proving the miss populated it
    assert await cache_get("anomalies:limit=7") is not None


async def test_different_limits_use_different_keys():
    await cache_delete("anomalies:limit=3")
    await cache_delete("anomalies:limit=9")
    async with await _client() as c:
        await c.get("/anomalies?limit=3")
        await c.get("/anomalies?limit=9")
    assert await cache_get("anomalies:limit=3") is not None
    assert await cache_get("anomalies:limit=9") is not None


async def test_endpoint_still_works_when_redis_is_down():
    """Graceful degradation end-to-end: 200 from Postgres, not a 500."""
    with patch("src.services.cache._client") as fake:
        fake.get.side_effect = ConnectionError("redis is down")
        fake.set.side_effect = ConnectionError("redis is down")
        async with await _client() as c:
            resp = await c.get("/anomalies?limit=5")
    assert resp.status_code == 200, "service must survive a Redis outage"
    assert isinstance(resp.json(), list)
