"""Acceptance tests for MICRO-3.0. DO NOT EDIT THIS FILE.

Run the seed script first, then:
  TESTING=1 pytest tests/test_seed_distribution.py -v
"""

import os

import pytest
from sqlalchemy import create_engine, text

SYNC_URL = os.environ.get(
    "DATABASE_URL_SYNC",
    "postgresql+psycopg2://analytics:analytics@localhost:5432/analytics",
)


@pytest.fixture(scope="module")
def engine():
    eng = create_engine(SYNC_URL)
    yield eng
    eng.dispose()


def test_no_single_user_dominates(engine):
    sql = text(
        "SELECT max(cnt)::float / (SELECT count(*) FROM events) "
        "FROM (SELECT count(*) cnt FROM events GROUP BY user_id) s"
    )
    with engine.connect() as c:
        share = float(c.execute(sql).scalar())
    assert share <= 0.05, (
        f"heaviest user holds {share:.1%} of events — distribution is "
        "degenerate (was ~65% with raw truncated paretovariate)"
    )


def test_top_decile_holds_a_realistic_share(engine):
    sql = text(
        """
        WITH counts AS (
            SELECT user_id, count(*) cnt FROM events GROUP BY user_id
        ), ranked AS (
            SELECT cnt, ntile(10) OVER (ORDER BY cnt DESC) AS decile FROM counts
        )
        SELECT sum(cnt) FILTER (WHERE decile = 1)::float / sum(cnt) FROM ranked
    """
    )
    with engine.connect() as c:
        share = float(c.execute(sql).scalar())
    assert 0.35 <= share <= 0.70, (
        f"top 10% of users hold {share:.1%} — expected 35-70% for a realistic "
        "long tail (too high = degenerate, too low = uniform)"
    )


def test_enough_distinct_users(engine):
    with engine.connect() as c:
        n = c.execute(text("SELECT count(DISTINCT user_id) FROM events")).scalar()
    assert n >= 2000, f"only {n} distinct users — the tail is not being reached"


def test_still_a_power_law_not_uniform(engine):
    sql = text(
        "SELECT max(cnt)::float / avg(cnt) FROM "
        "(SELECT count(*) cnt FROM events GROUP BY user_id) s"
    )
    with engine.connect() as c:
        skew = float(c.execute(sql).scalar())
    assert skew > 5, f"skew {skew:.1f} — distribution looks uniform, not long-tailed"
