"""initial schema

Revision ID: 8db1130e556e
Revises: 
Create Date: 2026-07-20 12:16:25.468905

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8db1130e556e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('events',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('occurred_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('ingested_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('anomaly_score', sa.DOUBLE_PRECISION(), nullable=True),
    sa.Column('is_anomaly', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('model_version', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_events_anomalies', 'events', [sa.literal_column('occurred_at DESC')], unique=False, postgresql_where=sa.text('is_anomaly IS true'))
    op.create_index('idx_events_occurred_at', 'events', [sa.literal_column('occurred_at DESC')], unique=False)
    op.create_index('idx_events_user_time', 'events', ['user_id', sa.literal_column('occurred_at DESC')], unique=False)
    op.create_table('ingestion_batches',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('request_id', sa.String(length=64), nullable=False),
    sa.Column('event_count', sa.Integer(), nullable=False),
    sa.Column('failed_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('started_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('completed_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('model_registry',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('version', sa.String(length=20), nullable=False),
    sa.Column('trained_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('f1_score', sa.DOUBLE_PRECISION(), nullable=True),
    sa.Column('training_rows', sa.BigInteger(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('artifact_path', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('version')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('model_registry')
    op.drop_table('ingestion_batches')
    op.drop_index('idx_events_user_time', table_name='events')
    op.drop_index('idx_events_occurred_at', table_name='events')
    op.drop_index('idx_events_anomalies', table_name='events', postgresql_where=sa.text('is_anomaly IS true'))
    op.drop_table('events')
    # ### end Alembic commands ###
